#pragma once

#define FAECHECK_VERSION_MAJOR  1
#define FAECHECK_VERSION_MINOR  0
#define FAECHECK_VERSION_PATCH  0

// aux. macros to export the above numbers in various formats
#define _FAECHECK_STRINGIFY2(str) #str
#define _FAECHECK_STRINGIFY(str) _FAECHECK_STRINGIFY2(str)
#define FAECHECK_VERSION_STR _FAECHECK_STRINGIFY(FAECHECK_VERSION_MAJOR) "." _FAECHECK_STRINGIFY(FAECHECK_VERSION_MINOR) "." _FAECHECK_STRINGIFY(FAECHECK_VERSION_PATCH) ".0"
#define FAECHECK_VERSION_RSRC FAECHECK_VERSION_MAJOR,FAECHECK_VERSION_MINOR,FAECHECK_VERSION_PATCH,0
